### ISSUE TITLE
您好，刚刚拜读了您的论文，但是其中我有一个数学上的小疑问，希望您的给予解答

### ISSUE THREAD

**Issue by wmathor** [RunxinXu/ChildTuning#2]
公式17，为什么系数是p/p，我不太明白分子的p是从哪里变换过来的，水平有限，还麻烦您解答一下，谢谢啦

**Comment by RunxinXu** [comment]
感谢你的关注。我觉得分子上的p应该是E(M)来的，其中M是从伯努利分布采样得到的mask。

**Comment by wmathor** [comment]
> 感谢你的关注。我觉得分子上的p应该是E(M)来的，其中M是从伯努利分布采样得到的mask。

明白了，非常感谢
